### ISSUE TITLE
[Bug] - Blade directive is removing all spaces

### ISSUE THREAD

**Issue by amandiobm** [jamesmills/laravel-timezone#10]
When defining a format using the blade directive, all spaces inside the format are removed by `str_replace`.

**Comment by jamesmills** [comment]
I have absolutely no idea why I did this. There must have been a reason but I cannot think of what it was. I have also noticed that the formatting was not right, I just haven't had time to look into it so thank you very much for this.

**Comment by jamesmills** [comment]
Thank you for the PR.

**Comment by amandiobm** [comment]
> I have absolutely no idea why I did this. There must have been a reason but I cannot think of what it was. I have also noticed that the formatting was not right, I just haven't had time to look into it so thank you very much for this.

It happens :)

> Thank you for the PR.

Welcome ;)
