### ISSUE TITLE
[Feature] - Ability to choose which flash message to use

### ISSUE THREAD

**Issue by amandiobm** [jamesmills/laravel-timezone#14]
Give the ability to choose what flash message we want to use to display the messages.

Why: Make it possible to turn off the flash message or use other flash message package such as `mercuryseries/flashy`, `spatie/laravel-flash`, `mckenziearts/laravel-notify`, etc.

Solution: On the configuration file we already have the `flash` attribute to define which package we want to use. Use that to turn off all flash messages `'flash' => 'off'`, and also a way to integrate other packages `'flash' => 'mercuryseries'`, `'flash' => 'spatie'`, `'flash' => 'mckenziearts'`, etc.

Cheers!

**Comment by jamesmills** [comment]
Awesome work as always @amandiobm. 

Thank you.
