### ISSUE TITLE
[Hot-Fix]: Null as first param on convertToLocal method.

### ISSUE THREAD

**Issue by amandiobm** [jamesmills/laravel-timezone#18]
At `Timezone::convertToLocal` has an `if` statement which checks if the date is not `null`. That statement is never reached because the method signature required the first param to be a `Carbon` Object.

I had sometimes my date are null which broke the `@displayDate` directive.

**Comment by jamesmills** [comment]
Interesting, I know that if you set a datetime on an object as nullable then I have seen errors thrown when using the @displayDate directive. I guess we should return null also if it's null.

**Comment by amandiobm** [comment]
Well, I prefer as it is. Return as string message. Making that message configurable on the config file.

If returned as null, have no point to accept. Because we will have to test returned value from the directive. Adding more code into the app not into the package.

Cheers.

**Comment by jamesmills** [comment]
https://github.com/jamesmills/laravel-timezone/pull/19

**Comment by jamesmills** [comment]
Tagged as 1.8.1 (I think this is the right way to version it)

**Comment by amandiobm** [comment]
Agreed.
