### ISSUE TITLE
Always saving default timezone on localhost.

### ISSUE THREAD

**Issue by maverick504** [jamesmills/laravel-timezone#21]
Hi!

User timezone value are always been saved as 'America/New_York', or wathever the default timezon in geoip config is.

It is because i'm on localhost? Or maybe I've missed something during installation?

Thanks in advance!

**Comment by amandiobm** [comment]
@maverick504 Yep. Since a localhost IP address is `127.0.0.1`, GeoIP can not find a valid match so for that it will be using the default one. If the majority of your user is not in the default timezone, I would suggest exporting the GeoIP config file and change the default timezone. I did that in my case.

**Comment by maverick504** [comment]
@amandiobm Ohhh i see. Thank you!

**Comment by jamesmills** [comment]
This is certainly the best answer. Thank you @amandiobm

**Comment by d4rkd0s** [comment]
Just noting here, so maybe it helps other folks...
I also experienced this with [**Laravel Vapor**](https://vapor.laravel.com/)

But as a workaround this works on 95% of browsers...

```
<input id="tz" name="tz" type="hidden">
<script>
window.onload = function(){
    document.getElementById("tz").value = Intl.DateTimeFormat().resolvedOptions().timeZone;
}
</script>
```

Then change your `AuthenticatedSessionController.php`

`store()` method, to now include, `Auth::user()->timezone = $request->tz;`

```
public function store(LoginRequest $request)
{
    $request->authenticate();

    $request->session()->regenerate();

    $user = Auth::user();
    $user->timezone = $request->tz;
    $user->save();

    return redirect()->intended(RouteServiceProvider::HOME);
}
```

If you need the `timezone` column, the migration is as follows, (credit [this repo](https://github.com/jamesmills/laravel-timezone/blob/master/src/database/migrations/add_timezone_column_to_users_table.php.stub))
```
if (!Schema::hasColumn('users', 'timezone')) {
    Schema::table('users', function (Blueprint $table) {
        $table->string('timezone')->after('remember_token')->nullable();
    });
}
```
