### ISSUE TITLE
Method `ConvertFromLocal` should add `time` when is not present.

### ISSUE THREAD

**Issue by amandiobm** [jamesmills/laravel-timezone#22]
Method `ConvertFromLocal` should add `time` when is not present.

When called the method using `2020-01-01` with no `time` the method it simply returns the date in "UTC format".

Should this method add the `time` when it is not preset?!

cheers.

**Comment by jamesmills** [comment]
Why would anyone call this if it was not using a date input value?

Makes me think maybe you could use the trait to automatically do this on a submitted request value. You would simple add the value to the model like you would with adding additional datetime options?

**Comment by jamesmills** [comment]
@amandiobm do you still see this is as an issue?
