### ISSUE TITLE
You have to publish config to use package

### ISSUE THREAD

**Issue by jamesmills** [jamesmills/laravel-timezone#24]
We say it's optional to publish the config but it's not. If you use the package without the config published it cannot get the default `config('timezone.lookup')`. 

```
foreach (config('timezone.lookup') as $type => $keys) {
```

Not sure if we are doing something wrong with using default values?

**Comment by amandiobm** [comment]
I will double-check that.

**Comment by amandiobm** [comment]
PR #28
