### ISSUE TITLE
api user update

### ISSUE THREAD

**Issue by RolandVerner** [jamesmills/laravel-timezone#27]
i am using laravel passport and the package not update the user time zone in database

**Comment by amandiobm** [comment]
Hey @RolandVerner, can you send us the Laravel version? I will install the same version, with passport and test it.

cheers.

**Comment by amandiobm** [comment]
Hey @RolandVerner, I installed the latest version of Laravel, with the latest passport version. I noticed the passport package handles differently the login events. We will be looking to adjust that.

Thanks, for the feedback.

**Comment by jamesmills** [comment]
Hi @RolandVerner and thanks for submitting the issue!

Thank you @amandiobm for taking a look at this. Looks like there is a conflict on the #29 PR.

**Comment by amandiobm** [comment]
I'll be fixing pretty soon. tks.

**Comment by amandiobm** [comment]
Fixed ;)

**Comment by jamesmills** [comment]
Fixed and tagged in 1.9.2

**Comment by RolandVerner** [comment]
thanks
