### ISSUE TITLE
Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by sharkyenergy** [jamesmills/laravel-timezone#33]
Hello!

Installed as shown, but once i Login i Get the message "Invalid argument supplied for foreach()".

here:

```
        /**

    * @return mixed

    */

    private function getFromLookup()

    {

        $result = null;

 

        foreach (config('timezone.lookup') as $type => $keys) {

            if (empty($keys)) {

                continue;

            }

 

            $result = $this->lookup($type, $keys);

 

            if (is_null($result)) {

                continue;

            }

        }

 

        return $result;

    }

 

    /**
```

**Comment by SteaveAshmore** [comment]
I am also facing this issue.

**Comment by SteaveAshmore** [comment]
Somehow application is unable to load timezone configurations, in order to resolve run 
`php artisan config:cache` or `php artisan config:clear`, 
If still don't work publish timezone config using below command and then run above command.
`php artisan vendor:publish --provider="JamesMills\LaravelTimezone\LaravelTimezoneServiceProvider" --tag=config`

**Comment by jamesmills** [comment]
Hi @sharkyenergy it looks like you have stumbled across a problem others have had where you had your config cached before installing the package. I see @SteaveAshmore found and shared the solution.

I'm going to see if I can clear the config as part of the install in the composer.json file.

**Comment by jfsullivan** [comment]
I saw this error after pushing this package to production.   The solution given did not work for me.  I had to uninstall so that my users could login.  Hopefully there is another way to resolve it as I would like to use this package.

**Comment by jfsullivan** [comment]
Disregard the previous message.  After I got past this config issue, it was failing due to the tagging issue.  I switched to Redis, reinstalled, cleared the cache per the solution above and all is good.

Thanks!
