### ISSUE TITLE
Support Money as well ? (Enhancement)

### ISSUE THREAD

**Issue by dgillier** [jamesmills/laravel-timezone#38]
Hello,

Any chance that you will support Money as well (as geoIP is also supporting it) ?
Thanks, 
Denis

**Comment by jamesmills** [comment]
Hi Denis, 

I think as the package is focused on Timezones then we shouldn't look at adding other things into it.

You could hook into the underlying geoIP package to save this info on the user if you wanted to.

I find money is a rather complex thing so we could store the users local currency on the user model but I wouldn't want to get into trying to then show the user money in their local currency. I would suggest looking at something like https://github.com/cknow/laravel-money for this.

Thanks,

James
