### ISSUE TITLE
Method 'convertFromLocal' should convert local time to Laravel Default Timezone, not UTC

### ISSUE THREAD

**Issue by tarikhagustia** [jamesmills/laravel-timezone#39]
Hi, thanks for great laravel package, i think Method 'convertFromLocal' should convert local time to Laravel Default Timezone, not UTC due some application use different Timezone

**Comment by amandiobm** [comment]
Yep, I agree. Although I would recommend always to use on UTC when persisting dates and then changed to the desired timezone ;)

We will be fixing that soon tks.

**Comment by jamesmills** [comment]
Interesting comment, thanks @tarikhagustia for your suggestion.

My argument for this is that I am trying to push for best practice when dealing with timezones and it's always best to set your application to UTC and then use package like this to adjust the timezone as needed when dealing with the timezone or displaying them.

However, I do understand that some application may have a requirement to set the timezone to something other than UTC.

To add additional functionality to the package may I suggest you open a PR and where we use the applications config for timezone rather then forcing it to be UTC. 

Open to others thoughts on this, thanks again.

**Comment by wrabit** [comment]
Just my 2 cents, having worked in a timezone heavy related project, it's a very simple concept to use UTC as the persisted timezone and the go-between to build your local times from this. A big reason for us was because UTC is not effected by any daylight saving times.

**Comment by jamesmills** [comment]
Thanks again @wrabit for your comment. I'm going to close this because I still think using UTC as a default is best practice.

Happy to open this up again if you strongly disagree or if this is causing you big issues in a project you are working on.
