### ISSUE TITLE
No way of getting user IP when behind a load balancer

### ISSUE THREAD

**Issue by RykWaters** [jamesmills/laravel-timezone#43]
It seems that timezone is always saved as "America/New_York".
This seems to be some sort of default / localhost value.

I now have to do another check after login to see if NULL or "America/New_York" and update accordingly.

All of my calls to `geoip()->getLocation()` seem to work correctly, so don't know what's happening in in this library's Login listener that fails.

**Comment by RykWaters** [comment]
looks like this is due to being behind a load balancer.
With the current config, i'm not sure if there is a way to generate ip using a custom method, rather than a custom key on the request objects

Or just skip getting the client IP here and let geoip handle it

**Comment by jamesmills** [comment]
Hi @RykWaters and thanks for using the package!

When I use the package locally using Laravel Valet it always sets my timezone as "America/New_York" which is frustrating but I just thought it was something I had to put up with and I haven't given it much thought.

I know we did have some issues with someone behind a load balancer which was setting the IP in a different location so we enabled a config to allow the user to set where to get the IP from https://github.com/jamesmills/laravel-timezone#lookup-array

By default, it will look in `$ip = $request->server->get('REMOTE_ADDR')` to get the IP address and then pass this through to `$geoip_info = geoip()->getLocation($ip)`

I see that the geoip package actually has a default option to use `geoip()->getLocation()` which will try automagically find the IP for the user. 

I wonder if we should add this as our default option. So by default the package should just use `geoip()->getLocation()` and not pass an IP, unless you set in the config to use a specific location. @amandiobm what do you think? I was looking at how the geoip package get's the IP and it's actually to some quite substantial checks https://github.com/Torann/laravel-geoip/blob/master/src/GeoIP.php#L230

Thanks

**Comment by RykWaters** [comment]
before you worry too much, i'm just trying what happens when you pass null to it.

In which case, if you have no keys in the config, then it'll work

**Comment by RykWaters** [comment]
yes, it appears that if you just comment out all config options, then geoip handles it quite well. So possibly just a docs update for now, similar to the cache issue.

"If behind a load balancer comment out all sections in 'lookup'"

then you can decide more fundamental changes later

**Comment by RykWaters** [comment]
Ok, after a little more digging. Obviously you did set up the lookup array.

But unfortunately for those of us using AWS EB we don't get a single IP in there, we also get any proxies, separated by comma. Removed full IP obviously
`"x-forwarded-for" => array:1 [▼
        0 => "90.x.x.x, 162.x.x.x"
      ]`

so i suggest either a tweak to the lookup code to only return up to the first comma. Or, as above, just tell people to not try and find the ip themselves at all.

**Comment by MeowKim** [comment]
@RykWaters  
The **last** one in the list of `HTTP_X_FORWARDED_FOR`   is the IP that connected to your (reverse) proxy when using AWS ELB.

**Comment by jeremykenedy** [comment]
@jamesmills @RykWaters 
Is there any update on. I love your work and your package. This is an issue we are having the same environment as outlined above.

Any updates are appreciated.

Thanks!

**Comment by spacemudd** [comment]
For behind CloudFlare and Docker:

`php artisan vendor:publish --provider="JamesMills\LaravelTimezone\LaravelTimezoneServiceProvider" --tag=config`

config/timezone.php:

    'lookup' => [
        'server' => [
            //'REMOTE_ADDR',
        ],
        'headers' => [
            'cf-connecting-ip',
        ],
    ],

Worked as expected for setting up the correct users' timezones.

**Comment by danalexandrucraciun** [comment]
Hi James, 

Because I had some issues with defining the header REMOTE_ADDR i used to replace it with something. 
sed -i 's/REMOTE_ADDR/X-Hdr-01/g' /var/www/laravel/vendor/jamesmills/laravel-timezone/src/Listeners/Auth/UpdateUsersTimezone.php

Unfortunately, i can't find it anymore in UpdateUsersTimezone.php. 

Can you please be so kind and tell a little bit about this change? What should i look for? 

Thanks, 
Dan

**Comment by amandiobm** [comment]
Hey @danalexandrucraciun, take a look at our `config/timezone.php`. The comment above yours has an example of how to use it, and also has the docs.

But essentially the lookup config is how you tell the package from where you want him to grab the IP and sent to GEOLocation.

**Comment by smnmmnn** [comment]
For everyone using Laravel Vapor — in `config/timezone.php`, change the `loopup` to the following to get the correct user IP:
`    'lookup' => [
        'server' => [
            // 'REMOTE_ADDR',
        ],
        'headers' => [
            'x-vapor-source-ip'
        ],
    ],`

**Comment by swaaj** [comment]
> For everyone using Laravel Vapor — in `config/timezone.php`, change the `lookup` to the following to get the correct user IP:
> 
> ```
> 'lookup' => [
>     'server' => [
>         // 'REMOTE_ADDR',
>     ],
>     'headers' => [
>         'x-vapor-source-ip'
>     ],
> ],
> ```

Thank you, you've saved me a lot of time !
