### ISSUE TITLE
Timezone will be saved automatically? or have to saved manually?

### ISSUE THREAD

**Issue by rutul8897** [jamesmills/laravel-timezone#45]
As described in the package description, I have published the vendor and it has added the timezone field to my users table migration file. I have migrated and it has added this field to table 
but when I registered or login user it is not automatically updated timezone of the user in the database.

here is my code

`$time =  Timezone::convertToLocal($user->created_at);`

Please do needful

**Comment by jamesmills** [comment]
Hi,

Where do you have that code? You shouldn't have to do anything, it should happen on the user events.

This package listens for the `\Illuminate\Auth\Events\Login`

James

**Comment by jamesmills** [comment]
I'm assuming that this is no longer an issue, thanks for your question and I hope you continue to enjoy using the package. If you have any further issues please don't hesitate to open another issue. Thanks, James
