### ISSUE TITLE
use in model

### ISSUE THREAD

**Issue by MohammaddReza** [jamesmills/laravel-timezone#48]
i want to use this command in my model like this:
```
    public function getTimeAttribute($value){
        return Timezone::convertFromLocal($this->start);
    }
```
but it returns this error:
Class 'App\Timezone' not found

**Comment by MohammaddReza** [comment]
now i have this error:
`Non-static method JamesMills\LaravelTimezone\Timezone::convertToLocal() should not be called statically`
im using vue (not blade) and i have to use this with api
this is my function:
```
    public  function getTimeAttribute(){
        return Timezone::convertToLocal($this->created_at);
    }
```

**Comment by SamuelNitsche** [comment]
Sorry, my bad. The package offers a Facade. You should use this one.
So please replace use `JamesMills\LaravelTimezone\Facades\Timezone`

**Comment by MohammaddReza** [comment]
thank you this is work very well.

**Comment by SamuelNitsche** [comment]
So the issue is fixed?

**Comment by jamesmills** [comment]
Sorry I'm late to review this @MohammaddReza.

Thank you very much @SamuelNitsche for taking the time to provide help and a solution.

Stay safe!
