### ISSUE TITLE
UpdateUsersTimezone gives wrong info

### ISSUE THREAD

**Issue by AEK-BKF** [jamesmills/laravel-timezone#52]
Hi,

Thanks for this nice package,
I've integrated it on live server, and I'm using ipgeolocation service in geoip package config.
So, I found this bug here :
```
if (config('timezone.overwrite') == true || $user->timezone == null) {
                $user->timezone = $geoip_info['timezone'];
                $user->save();
                $this->notify($geoip_info);
 }
```
This : `$geoip_info['timezone']` returns Null
Here dd($geoip_info) (See Attached)
So to fix it :
` $user->timezone = $geoip_info->time_zone['name'];

![bug](https://user-images.githubusercontent.com/16412739/94084274-d46a7d00-fe0d-11ea-9053-186c1a756aee.png)
`

Thanks.

**Comment by jamesmills** [comment]
Hi @AEK-BKF 

Ahhhh, OK. I understand. I thought that `torann/geoip` would standardize the returned data so we wouldn't see this issue.

I guess we could put something like 

```
$user->timezone = $geoip_info['timezone'] ?? $geoip_info->time_zone['name'];
```

If you can test and submit a PR for this I will accept it, thanks.

**Comment by jamesmills** [comment]
@AEK-BKF are you still having this issue? Any chance you could PR the solution?

**Comment by maher1337** [comment]
Hey @jamesmills I created a PR https://github.com/jamesmills/laravel-timezone/pull/76
