### ISSUE TITLE
update torann/geoip to v3

### ISSUE THREAD

**Issue by aavinseth** [jamesmills/laravel-timezone#54]
![image](https://user-images.githubusercontent.com/5337520/97953235-e56fbc00-1dc5-11eb-902c-153375f20ae0.png)

**Comment by wrabit** [comment]
hitting this also

**Comment by themasterpage** [comment]
Need as well, any plans for this?

**Comment by keenminded** [comment]
@wrabit @themasterpage if you are still experiencing this, you can use my fork until this repository is updated.

In your composer.json add:
```
"repositories": [
    {
        "type": "vcs",
        "url": "https://github.com/keenminded/laravel-timezone"
    }
],
```

In require section change or add:
```
"jamesmills/laravel-timezone": "dev-forked",
```

This will load torann/geoip, and also supports PHP8.

**Comment by jamesmills** [comment]
Hi all,

Sorry to be late to the party.

Just to be clear, we're having issue because we need to update `torann/geoip` to the latest version? 

@keenminded if you have fixed this could you do a PR with your fixes to the package and I will merge them in.

Thanks all

**Comment by keenminded** [comment]
Hi @jamesmills,

Just submitted the PR. Please let me know if anything needs to be updated. Thanks!
