### ISSUE TITLE
Make database migration publishable

### ISSUE THREAD

**Issue by DariusIII** [jamesmills/laravel-timezone#6]
It would be very useful to make the included migration publishable and to use current date for filename.
I am having issues with your package trying to update users table that has not yet been created.

**Comment by amandiobm** [comment]
I just open a PR #7 to handle this request. Feel free to make comments ;)

**Comment by jamesmills** [comment]
Hi @amandiobm thanks for that! I have made a couple of comments on the PR. Thanks for doing this, extremely helpful.

**Comment by amandiobm** [comment]
No worries @jamesmills, my pleasure. I'll be checking the comments in a bit. ;)

**Comment by jamesmills** [comment]
This has been done and merged 

https://github.com/jamesmills/laravel-timezone/pull/7

Thank you @amandiobm
