### ISSUE TITLE
Complications when server uses proxies

### ISSUE THREAD

**Issue by ridz1208** [jamesmills/laravel-timezone#8]
I'm using this package successfully on my own server. However when trying to install it on  a secondary server using proxies, it fails. It seems to rely on the `REMOTE_ADDR` header for the IP however my ITs are informing me that the real client IP is stored in a different header because of the proxy.

Is it possible to make the IP source configurable instead of pointing to REMOTE_ADDR only ?

**Comment by jamesmills** [comment]
Hi @ridz1208 

You could certainly add this as a config option. 

How do you fancy submitting a PR for this?

Thanks, James

**Comment by jamesmills** [comment]
It's live @ridz1208. Thanks @amandiobm :-)
