### ISSUE TITLE
Laravel 10 support update please.

### ISSUE THREAD

**Issue by jackkitley** [jamesmills/laravel-timezone#88]
Please could you update to support laravel 10 install.

**Comment by jamesmills** [comment]
@jackkitley just tagged a new version which I think will help.

**Comment by jackkitley** [comment]
@jamesmills only see 1.11. is there a 1.12?

https://packagist.org/packages/jamesmills/laravel-timezone

thanks

**Comment by jamesmills** [comment]
Sorry, just pushed the tag and refreshed Packagist. 

Try again now, thanks.
