### ISSUE TITLE
[Feature] - Have the ability to define the default date format.

### ISSUE THREAD

**Issue by amandiobm** [jamesmills/laravel-timezone#9]
Hey @jamesmills,

I would like to be able to define the default date formate using the configuration file.

Why: When using the directive `@displayDate`, 99% of my cases I will have to define the format.

Solution: Use the configuration file to define the most used format and only define the directives the exceptions.

Feel free to question.

Cheers.

**Comment by jamesmills** [comment]
Love this idea. Please feel free to PR it. I will try to be more responsive to this one.

**Comment by jamesmills** [comment]
Wonderful, thank you.

**Comment by amandiobm** [comment]
Welcome. :)
