### ISSUE TITLE
Issue with require

### ISSUE THREAD

**Issue by jackkitley** [jamesmills/laravel-timezone#92]
Problem 1
    - jamesmills/laravel-timezone[dev-master, 1.12.0, ..., 1.13.0] require torann/geoip ^3.0 -> satisfiable by torann/geoip[3.0.1, 3.0.2, 3.0.3, 3.0.4].
    - jamesmills/laravel-timezone[dev-pullrequests/keenminded/forked, dev-pullrequests/jonnymccullagh/diffForHumans, 1.9.3, ..., 1.10.0] require laravel/framework 5.6.* || 5.7.* || 5.8.* || ^6 || ^7 || ^8 -> found laravel/framework[v5.6.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but it conflicts with your root composer.json require (^10.0).
    - jamesmills/laravel-timezone dev-laravel-8-security-updates requires laravel/framework 5.6.* || 5.7.* || 5.8.* || ^6 || ^7 || ^8.24.0 -> found laravel/framework[v5.6.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.24.0, ..., 8.x-dev] but it conflicts with your root composer.json require (^10.0).
    - jamesmills/laravel-timezone[1.0.0, ..., 1.0.4] require illuminate/auth ^5.6 -> found illuminate/auth[v5.6.0, ..., 5.8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - jamesmills/laravel-timezone[1.0.5, ..., 1.0.6] require illuminate/auth 5.6.* -> found illuminate/auth[v5.6.0, ..., 5.6.x-dev] but these were not loaded, likely because it conflicts with another require.
    - jamesmills/laravel-timezone[1.1.0, ..., 1.2.1] require laravel/framework 5.6.* || 5.7.* || 5.8.* -> found laravel/framework[v5.6.0, ..., 5.8.x-dev] but it conflicts with your root composer.json require (^10.0).
    - jamesmills/laravel-timezone[1.3.0, ..., 1.8.1] require laravel/framework 5.6.* || 5.7.* || 5.8.* || ^6 -> found laravel/framework[v5.6.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev] but it conflicts with your root composer.json require (^10.0).
    - jamesmills/laravel-timezone[1.9.0, ..., 1.9.2] require laravel/framework 5.6.* || 5.7.* || 5.8.* || ^6 || ^7 -> found laravel/framework[v5.6.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but it conflicts with your root composer.json require (^10.0).
    - jamesmills/laravel-timezone 1.11.0 requires laravel/framework 5.6.* || 5.7.* || 5.8.* || ^6 || ^7 || ^8 || ^9 -> found laravel/framework[v5.6.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev] but it conflicts with your root composer.json require (^10.0).
    - torann/geoip 3.0.1 requires php ^7.2 -> your php version (8.2.2) does not satisfy that requirement.
    - torann/geoip[3.0.2, ..., 3.0.3] require illuminate/support ^8.0 -> found illuminate/support[v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - torann/geoip 3.0.4 requires illuminate/cache ^8.0|^9.0 -> found illuminate/cache[v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires jamesmills/laravel-timezone * -> satisfiable by jamesmills/laravel-timezone[dev-master, dev-laravel-8-security-updates, dev-pullrequests/jonnymccullagh/diffForHumans, dev-pullrequests/keenminded/forked, 1.0.0, ..., 1.13.0, 9999999-dev].

**Comment by jackkitley** [comment]
Problem 1
    - torann/geoip 3.0.1 requires php ^7.2 -> your php version (8.2.2) does not satisfy that requirement.
    - torann/geoip[3.0.2, ..., 3.0.3] require illuminate/support ^8.0 -> found illuminate/support[v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - torann/geoip 3.0.4 requires illuminate/cache ^8.0|^9.0 -> found illuminate/cache[v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev] but these were not loaded, likely because it conflicts with another require.
    - jamesmills/laravel-timezone 1.13.0 requires torann/geoip ^3.0 -> satisfiable by torann/geoip[3.0.1, 3.0.2, 3.0.3, 3.0.4].
    - Root composer.json requires jamesmills/laravel-timezone ^1.13.0 -> satisfiable by jamesmills/laravel-timezone[1.13.0].

**Comment by jamesmills** [comment]
OK looks like `torann/geoip` has some fixed requirements for the old illuminate stuff.

https://github.com/Torann/laravel-geoip/blob/master/composer.json#L20

Also looks like there is an open PR to for L10 https://github.com/Torann/laravel-geoip/pull/223


I'll wait to see if this gets merged and if not then I'll switch out to use [stevebauman/location](https://github.com/stevebauman/location) but I think this would require a major version tag (breaking change).

**Comment by jackkitley** [comment]
Ah sorry

I misread it as merged when I had a look but I see question asked 7 hours
ago.


Thanks

**Comment by jackkitley** [comment]
@jamesmills still open i see. odd that it isnt being merged.
